### ISSUE TITLE
Use docker multistage

### ISSUE THREAD

**Issue by vitaliimelnychuk** [WiseEngineering/crispy-api#6]
minor comment:
can be changed with docker multistage
https://docs.docker.com/develop/develop-images/multistage-build/

_Originally posted by @melnychukvitaliy in https://github.com/WiseEngineering/crispy-api/pull/5/files_

**Comment by Bazillius** [comment]
@melnychukvitaliy looks like we made these changes already and can close this issue [link](https://github.com/WiseEngineering/crispy-api/pull/5/files).
