### ISSUE TITLE
Add Config file with types

### ISSUE THREAD

**Issue by vitaliimelnychuk** [WiseEngineering/crispy-api#7]
this is good start 👍 

Thinking about moving all configuration into one file, where we will define types
will be something like 
https://github.com/WiseEngineering/crispy-cli/blob/master/src/config.ts
but, there is no need for user config as we will use environment variables for these purposes

_Originally posted by @melnychukvitaliy in https://github.com/WiseEngineering/crispy-api/pull/5/files_

**Comment by Bazillius** [comment]
[PR](https://github.com/WiseEngineering/crispy-api/pull/10/)
